### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ACod00** [crabshank/Draw-3D-straight-lines-on-2D-images#2]
Hi, this project is great, just one thing, can you add a vertical line like this dotted line in this picture to see if the shoulder or head is offside instead of the foot?

![skysports-jesse-lingard-offside_4939180](https://user-images.githubusercontent.com/74859616/196128529-2e72ca42-57cc-4294-b97d-92dc4ea1e923.jpg)

**Comment by wesleyfernandess** [comment]
yeah we need

**Comment by crabshank** [comment]
In real football, the vertical component is matched to real measurements on/of the pitch; without two parallel vertical points the same height off the ground its not possible to know the true vertical lines. 

Because of the above, any vertical line (other than the ones already there) will be pure guesswork.

See: [https://www.youtube.com/watch?v=PCOK7-kc_8o](url)

**Comment by crabshank** [comment]
Turns out I was wrong, I think I've done it, please try it.
